import { adapterHostContextSchema, clipboardVersionSchema, nativeTextChunkSchema, runtimeOperationIntentSchema } from "./adapters.ts"
import {
  browserInstanceSnapshotSchema,
  browserOperationRequestSchema,
  browserOperationResultSchema,
  browserTargetSnapshotSchema,
  deviceBrowserInstanceSnapshotSchema,
  deviceBrowserOperationRequestSchema,
  deviceBrowserOperationResultSchema,
  deviceBrowserTargetSnapshotSchema,
  deviceSnapshotSchema,
} from "./browser.ts"
import { capabilitySetSchema } from "./capabilities.ts"
import {
  browserCaptureRequestSchema,
  nativeBinaryFrameHeaderSchema,
  observationPublicationSchema,
  screenCaptureRequestSchema,
  screenCaptureResultSchema,
} from "./capture.ts"
import { contractErrorSchema } from "./errors.ts"
import { nativeDisplayMappingSchema, nativeEvidenceReportSchema, nativeTargetMappingSchema, verifiedNativeEvidenceReceiptSchema } from "./evidence.ts"
import {
  browserInstanceRefSchema,
  browserTargetRefSchema,
  deviceBrowserInstanceRefSchema,
  deviceBrowserTargetRefSchema,
  deviceRefSchema,
  fenceTokenSchema,
  nativeGenerationSchema,
  operationTargetSchema,
  processRefSchema,
  runtimeGenerationSchema,
  surfaceRefSchema,
  windowRefSchema,
} from "./identities.ts"
import {
  heldInputLedgerAckSchema,
  heldInputLedgerSnapshotSchema,
  nativeCancelAckSchema,
  nativeCancelRequestSchema,
  nativeDrainAckSchema,
  nativeDrainRequestSchema,
  nativeHeartbeatAckSchema,
  nativeHeartbeatRequestSchema,
  nativeOperationStatusSchema,
  nativeRecoveryLedgerStatusSchema,
  nativeStatusRequestSchema,
  nativeCleanupAckSchema,
  nativeCleanupControlSchema,
} from "./native-lifecycle.ts"
import { nativeAuditSessionSchema, nativeHandshakeRequestSchema, nativeHandshakeResponseSchema } from "./native.ts"
import { observedEventSchema, observerCoverageSchema } from "./observer.ts"
import {
  observationSchema,
  interactionPointProofSchema,
  proofRefSchema,
  readinessPolicySchema,
  readinessResultSchema,
} from "./observations.ts"
import {
  browserExecutionContextSchema,
  clipboardExecutionContextSchema,
  deviceExecutionContextSchema,
  nativeExecutionContextSchema,
  operationOutcomeSchema,
  operationRecordSchema,
  runtimeClientSessionSchema,
  serializableOperationContextSchema,
  targetPreconditionSchema,
} from "./operations.ts"
import { cleanupAuthorityReceiptSchema, cleanupOutcomeSchema, runtimeResourceHandleSchema, runtimeResourceRefSchema } from "./resources.ts"
import { lifetimeReservationHandleSchema, reservationCleanupReceiptSchema } from "./reservations.ts"
import { axInspectionRequestSchema, axInspectionResultSchema, cgOnlyWindowRecordSchema, desktopInventorySnapshotSchema, desktopWindowEntrySchema, surfaceRecordSchema, windowMappingEvidenceSchema, windowTransitionRequestSchema, windowTransitionResultSchema } from "./window.ts"

export const contractSchemaRegistry = {
  runtimeGeneration: runtimeGenerationSchema,
  nativeGeneration: nativeGenerationSchema,
  fenceToken: fenceTokenSchema,
  processRef: processRefSchema,
  windowRef: windowRefSchema,
  surfaceRef: surfaceRefSchema,
  browserInstanceRef: browserInstanceRefSchema,
  browserTargetRef: browserTargetRefSchema,
  deviceRef: deviceRefSchema,
  deviceBrowserInstanceRef: deviceBrowserInstanceRefSchema,
  deviceBrowserTargetRef: deviceBrowserTargetRefSchema,
  operationTarget: operationTargetSchema,
  capabilitySet: capabilitySetSchema,
  contractError: contractErrorSchema,
  nativeDisplayMapping: nativeDisplayMappingSchema,
  nativeTargetMapping: nativeTargetMappingSchema,
  nativeEvidenceReport: nativeEvidenceReportSchema,
  verifiedNativeEvidenceReceipt: verifiedNativeEvidenceReceiptSchema,
  runtimeClientSession: runtimeClientSessionSchema,
  targetPrecondition: targetPreconditionSchema,
  nativeExecutionContext: nativeExecutionContextSchema,
  browserExecutionContext: browserExecutionContextSchema,
  deviceExecutionContext: deviceExecutionContextSchema,
  clipboardExecutionContext: clipboardExecutionContextSchema,
  serializableOperationContext: serializableOperationContextSchema,
  operationOutcome: operationOutcomeSchema,
  operationRecord: operationRecordSchema,
  runtimeOperationIntent: runtimeOperationIntentSchema,
  adapterHostContext: adapterHostContextSchema,
  runtimeResourceRef: runtimeResourceRefSchema,
  runtimeResourceHandle: runtimeResourceHandleSchema,
  cleanupOutcome: cleanupOutcomeSchema,
  cleanupAuthorityReceipt: cleanupAuthorityReceiptSchema,
  lifetimeReservationHandle: lifetimeReservationHandleSchema,
  reservationCleanupReceipt: reservationCleanupReceiptSchema,
  nativeTextChunk: nativeTextChunkSchema,
  clipboardVersion: clipboardVersionSchema,
  nativeHandshakeRequest: nativeHandshakeRequestSchema,
  nativeAuditSession: nativeAuditSessionSchema,
  nativeHandshakeResponse: nativeHandshakeResponseSchema,
  nativeStatusRequest: nativeStatusRequestSchema,
  nativeOperationStatus: nativeOperationStatusSchema,
  nativeRecoveryLedgerStatus: nativeRecoveryLedgerStatusSchema,
  nativeHeartbeatRequest: nativeHeartbeatRequestSchema,
  nativeHeartbeatAck: nativeHeartbeatAckSchema,
  nativeCancelRequest: nativeCancelRequestSchema,
  nativeCancelAck: nativeCancelAckSchema,
  nativeCleanupControl: nativeCleanupControlSchema,
  nativeCleanupAck: nativeCleanupAckSchema,
  nativeDrainRequest: nativeDrainRequestSchema,
  nativeDrainAck: nativeDrainAckSchema,
  heldInputLedgerSnapshot: heldInputLedgerSnapshotSchema,
  heldInputLedgerAck: heldInputLedgerAckSchema,
  observerCoverage: observerCoverageSchema,
  observedEvent: observedEventSchema,
  proofRef: proofRefSchema,
  interactionPointProof: interactionPointProofSchema,
  readinessPolicy: readinessPolicySchema,
  readinessResult: readinessResultSchema,
  observation: observationSchema,
  observationPublication: observationPublicationSchema,
  screenCaptureRequest: screenCaptureRequestSchema,
  browserCaptureRequest: browserCaptureRequestSchema,
  nativeBinaryFrameHeader: nativeBinaryFrameHeaderSchema,
  screenCaptureResult: screenCaptureResultSchema,
  desktopInventorySnapshot: desktopInventorySnapshotSchema,
  desktopWindowEntry: desktopWindowEntrySchema,
  cgOnlyWindowRecord: cgOnlyWindowRecordSchema,
  surfaceRecord: surfaceRecordSchema,
  windowMappingEvidence: windowMappingEvidenceSchema,
  windowTransitionRequest: windowTransitionRequestSchema,
  windowTransitionResult: windowTransitionResultSchema,
  axInspectionRequest: axInspectionRequestSchema,
  axInspectionResult: axInspectionResultSchema,
  browserInstanceSnapshot: browserInstanceSnapshotSchema,
  browserTargetSnapshot: browserTargetSnapshotSchema,
  browserOperationRequest: browserOperationRequestSchema,
  browserOperationResult: browserOperationResultSchema,
  deviceSnapshot: deviceSnapshotSchema,
  deviceBrowserInstanceSnapshot: deviceBrowserInstanceSnapshotSchema,
  deviceBrowserTargetSnapshot: deviceBrowserTargetSnapshotSchema,
  deviceBrowserOperationRequest: deviceBrowserOperationRequestSchema,
  deviceBrowserOperationResult: deviceBrowserOperationResultSchema,
} as const

export type ContractSchemaName = keyof typeof contractSchemaRegistry
